name: Continuous Integration
on:
push:
branches:
   - main
   - jenk
  workflow_dispatch:

jobs:
  my_job:
  runs-on: self-hosted

steps:

- name: Show directory
  run: 'pwd'

- name: List files
  run: 'ls -al'

