name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  my_job:
    runs-on: self-hosted
    steps:
      - name: Show directory
        run: pwd

      - name: List files
        run: ls -al
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
        java-version: '17'
        distribution: 'zulu'
        
      - name: Show Java version
        run: "java -version"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
        ref: jenk
        
      - name: Show directory
        run: 'pwd'